Corrected fidelity of datetime.fromtimestamp()
adafruit/Adafruit_CircuitPython_datetime pull request #6
Opened 2021-03-05 23:33 UTC by cognitivegears

See issue #5 for more information about the issue and steps to reproduce.

2021-03-09 19:22 UTC, jepler requested changes
Thanks! It looks like one small clean-up is possible, let me know if I'm mistaken about it.

2021-03-09 19:22 UTC, jepler commented on adafruit_datetime.py
>              frac = 0
Can the assignment of `frac` be removed in the else branch?

2021-03-09 19:22 UTC, jepler commented on adafruit_datetime.py
> +            t = int(t)
I'm not sure whether this is more efficient than modf, but perhaps you determined it was.

2021-03-11 01:29 UTC, cognitivegears commented on adafruit_datetime.py
>              frac = 0
Removed, thanks!

2021-03-11 01:36 UTC, cognitivegears commented on adafruit_datetime.py
> +            t = int(t)
Reverted - this was part of testing to see if I could also resolve the timestamp on the fractional case, but was not effective. If we got rid of all of them we could get rid of a small amount of memory by removing the import on the math module, but doesn't seem worth it.

2021-03-11 02:04 UTC, jepler approved these changes
Thank you!  The Actions failures when linting the code can be ignored for the purposes of this PR.

2021-03-11 18:39 UTC, merged